# Generated by Django 5.1.5 on 2025-11-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinksstore',
            name='price_per_soda',
            field=models.IntegerField(default=11500),
        ),
        migrations.AddField(
            model_name='drinksstore',
            name='price_per_water',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
