# Generated by Django 5.1.5 on 2025-11-15 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drinksstore_price_per_soda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expend_type', models.CharField(choices=[('office', 'office'), ('payments', 'Payments'), ('food_allowance', 'Food_allowance'), ('other_activity', 'Other_activity')], default='none ', max_length=100)),
                ('info', models.CharField(max_length=10)),
                ('value_amount', models.IntegerField(default='000')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
