# Generated by Django 5.1.5 on 2025-11-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='trip_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
