# Generated by Django 5.1.5 on 2025-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_statistics_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='info',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='return_trip_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='trip_date',
            field=models.DateField(),
        ),
    ]
