# Generated by Django 5.1.5 on 2025-11-16 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_expenditure_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
